version: "3.9"

services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: unless-stopped
    ports:
      - "5433:5432"   # host:container
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data

volumes:
  auth_data:
